openshift/ibm-roks-toolkit

pkg/controllers/clusterversion/reconcile.go
Copy of https://github.com/openshift/hypershift-toolkit/pull/190
=> Ensure CVO upstream and channel are always empty

pkg/controllers/clusterversion/reconcile.go
Backport of https://github.com/openshift/ibm-roks-toolkit/pull/17
=> [release-4.3] Ensure CVO upstream and channel are always empty

assets/cluster-bootstrap/00000_namespaces-needed-for-monitoring.yaml, pkg/assets/bindata.go
Adds label needed to include the default router in prometheus metrics.
=> Bug 1825029: Add monitoring label to ingress namespace

assets/kube-apiserver/oauthMetadata.json, assets/oauth-openshift/oauth-browser-client.yaml, assets/oauth-openshift/oauth-challenging-client.yaml, assets/oauth-openshift/oauth-server-config.yaml, pkg/api/types.go, pkg/assets/bindata.go, pkg/cmd/render/manifests.go
Introduces field for ExternalOauthDNSName but defaults it to ExternalAPIDNSName if not set. This is just to facilitate testing and should have no functional impact.
=> Use explicit variable for OAuth DNS endpoint

assets/cluster-bootstrap/00000_namespaces-needed-for-monitoring.yaml, assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml, assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml, pkg/assets/bindata.go
Adds assets needed for v4.5:
- openshift-authentication namespace - required by CVO manifests (should be empty in ROKS cluster)
- security authentication controller role and rolebinding
=> Assets needed for v4.5 support

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/control-plane-operator/cp-operator-deployment.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
Prefer scheduling pods to nodes that already have pods from that cluster.
Added a clusterID label to pods to make this work.
=> Add pod affinity

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/control-plane-operator/cp-operator-deployment.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, pkg/assets/bindata.go
Bad things happen if the first character in the clusterID is a number
=> Quotes around clusterID label

pkg/cmd/cpoperator/operator-config.go, pkg/controllers/cmca/configmap_observer.go, pkg/controllers/cmca/setup.go, pkg/controllers/openshift_apiserver/controller.go, pkg/controllers/openshift_controller_manager/operator_client.go
The CA values that the CMCA controller uses to update the kube controller manager CA could potentially get out of sync in one of 2 ways:
- The event that resulted in the appearance of the CA configmap was somehow missed. In that case, it would take 10 hours to do a relist of the configmaps to update the CA.
- The configmap cached in memory somehow got out of date, but it's what was used to update the controller manager CA.
To mitigate these, the code has been changed to get the configmaps directly via client calls instead of using the lister, and reduced the relist interval for the informer to 10min, so in case an event was missed, it would be caught again in a relatively short amount of time.
=> Reduce reliance on cache in the controller manager CA controller

assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml, pkg/assets/bindata.go
Adds additional API group for rangeallocations resource in the cluster role for the security allocation controller. Only needed for 4.6+
=> Fix permissions for security allocation controller

Dockerfile.metrics, Makefile, assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/roks-metrics/roks-metrics-deployment.yaml, assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml, assets/roks-metrics/roks-metrics-push-gateway-service.yaml, assets/roks-metrics/roks-metrics-push-gateway-servicemonitor.yaml, cmd/metrics-pusher/main.go, pkg/assets/bindata.go, pkg/metrics_pusher/pusher.go, pkg/render/manifests.go
Adds push gateway to ROKS metrics image
Adds manifests to run push gateway inside child cluster and sets up a servicemonitor for it.
Creates a metrics-pusher utility to periodically push metrics produced by a source URL and into a given path in a cluster
Adds the metrics-pusher sidecar container to the CVO pod so that it can push metrics into the child cluster.
=> Use Prometheus PushGateway to push CVO metrics to user cluster

assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
Resolves issue where CVO stops applying manifests during an upgrade because the machineconfig and machineconfigpool CRD manifests are not present.
=> Include machineconfig/machineconfigpool CRD manifests in bootstrap manifests

assets/kube-apiserver/config.yaml, assets/kube-apiserver/kube-apiserver-secret.yaml, pkg/assets/bindata.go
Requires a new entry in the kube apiserver secret with the service account signer (same as in kube controller manager).
=> Enable service account issuer so that TokenRequests work

assets/cluster-bootstrap/openshift-install-configmap.yaml, pkg/assets/bindata.go
Configmap is required by `cluster_installer` metric to report invoker and version
=> Add openshift-install configmap to bootstrap

assets/roks-metrics/roks-metrics-deployment.yaml, assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml, pkg/assets/bindata.go
The resources needed by these pods are very small. In practice, I haven't seen them go over 0.5m for cpu and 30Mi for memory. Not sure that it's worth parameterizing. 
Fixes #85
=> Add resource requests to ROKS metrics pods

assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
Allows full customization of http get liveness and readiness probes ala:
```
apiserverLivenessProbe:
httpGet:
path: livez?exclude=etcd
initialDelaySeconds: 300
periodSeconds: 10
timeoutSeconds: 160
failureThreshold: 6
successThreshold: 1
```
The httpGet path, port and scheme have defaults appropriate to each
service. The associated times and thresholds use the Kubernetes defaults.
The following probes are currently provided:
- apiserver liveness and readiness
- kms liveness
- scheduler liveness
- controller-manager liveness
Without changes to the cluster.yaml the existing ROKS configuration
is used.
=> Support customization of control plane liveness and readiness probes

pkg/api/defaults.go
Default flags have changed in OCP since 4.3, this updates them to what we're currently using in 4.5
See https://github.com/openshift/machine-config-operator/blob/release-4.5/templates/master/01-master-kubelet/_base/files/kubelet.yaml#L31-L36
and https://github.com/openshift/api/blob/0a191b5b9bb0ff4bf39e44be0fb4ffd7381766d3/config/v1/types_feature.go#L114-L124
=> Update feature flags to mirror OCP

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
In 4.6 and later, the release payload contains manifests that will fail to apply if the flowcontrol API is not enabled in the Kube APIServer.
=> Enable flow control APIs for priority and fairness

assets/kube-apiserver/kube-apiserver-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
Cluster image-security provided by the [Portieris](https://github.com/IBM/portieris) admission controller is an upcoming feature for IKS clusters.  These changes provide support for Openshift clusters.
=> Portieris admission controller support

assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
These requests are important for scheduing and must be set.
=> Memory/CPU requests for manifests-bootstrapper

Dockerfile, go.mod
And earlier change bumped the go version for the cp-operator and metrics server.
Making the same change now for the toolkit.
=> Use go 1.15 for toolkit

Dockerfile, Dockerfile.cpoperator, Dockerfile.metrics
They seem to be functionally equivalent, and the new one is free of CVEs.
=> [4.6] Use openshift/origin-base instead of ubi

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/roks-metrics/roks-metrics-deployment.yaml, assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
Kept failing with
```
"waiting": {
"message": "container has runAsNonRoot and image will run as root",
"reason": "CreateContainerConfigError"
}
```
Seems to be running fine when `runAsUser: 1000` is set
=> Changed runAsNonRoot to runAsUser for roks metrics

.pre-commit-config.yaml, .secrets.baseline
pre-commit config is in place, as well as a secret baseline file.
=> Add detect-secrets tooling

assets/kube-apiserver/kube-apiserver-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
IBM Cloud likes to see HTTP requests in the kube-apiserver logs.
This adds optional kubeAPIServerVerbosity field to the cluster yaml.
Fixes: https://github.ibm.com/alchemy-containers/armada-update/issues/2039
=> Support setting kube-apiserver log verbosity

assets/kube-apiserver/kube-apiserver-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
Cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/159
IBM Cloud likes to see HTTP requests in the kube-apiserver logs.
This adds optional kubeAPIServerVerbosity field to the cluster yaml.
Fixes: https://github.ibm.com/alchemy-containers/armada-update/issues/2039
=> [release-4.6] Support setting kube-apiserver log verbosity

assets/kube-apiserver/kube-apiserver-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
Cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/159
IBM Cloud likes to see HTTP requests in the kube-apiserver logs.
This adds optional kubeAPIServerVerbosity field to the cluster yaml.
Fixes: https://github.ibm.com/alchemy-containers/armada-update/issues/2039
=> [release-4.5] Support setting kube-apiserver log verbosity

assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml, assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml, pkg/assets/bindata.go
The ingress-to-route controller role is needed by the openshift controller manager to handle the conversion of ingress resources to routes.
=> Add ingress-to-route controller role/rolebinding to bootstrap manifests

assets/cluster-bootstrap/00000_namespaces-needed-for-monitoring.yaml, pkg/assets/bindata.go
Adds namespace to bootstrap to prevent cvo error:
`"openshift-oauth-apiserver/prometheus-k8s" (468 of 546): resource may have been deleted`
=> [release 4.6] Add openshift-oauth-apiserver namespace to bootstrap namespaces

.secrets.baseline, assets/kube-apiserver/default-audit-policy.yaml, assets/oauth-apiserver/audit-policy.yaml, assets/openshift-apiserver/config.yaml, pkg/assets/bindata.go
Changed the ROKS 4.7 audit api version from ```audit.k8s.io/v1beta1``` to the GA version ```audit.k8s.io/v1```
Related to this [issue](https://github.ibm.com/alchemy-containers/armada-update/issues/2100)
=> Updated roks 4.7 audit api version

.secrets.baseline, assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml, pkg/assets/bindata.go
Added ```apiGroup: rbac.authorization.k8s.io``` to roleRef to prevent kubectl from failing.
Related to this [issue](https://github.ibm.com/alchemy-containers/armada-update/issues/2085)
=> Fixing ingress-to-route-controller syntax error

assets/cluster-bootstrap/cluster-infrastructure-02-config.yaml, pkg/assets/bindata.go
What this does: adds platform type to the Spec portion of the
Infrastructure resource that is synced to the guest cluster.
Why is it needed? The OpenShift console looks at Spec and not status to
determine platform type and decide whether an External storage cluster
is allowed. See https://bugzilla.redhat.com/show_bug.cgi?id=1952832
=> Specify platform type in Spec of Infrastructure resource

assets/cluster-bootstrap/cluster-network-01-crd.yaml, pkg/assets/bindata.go
Update networks.operator.openshift.io to use GA CRD API for ROKS versions 4.8+.
We need to do cherry pick this to ROKS 4.8+ only.
=> Update networks.operator.openshift.io to use GA CRD API for 4.8+

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/control-plane-operator/cp-operator-deployment.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-apiserver/oauth-apiserver-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
Added dedicated master support for ROKS 4 on following components
=> Add dedicated master support for ROKS 4

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/control-plane-operator/cp-operator-deployment.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
This the cherrypick for [release-4.6](for the https://github.com/openshift/ibm-roks-toolkit/pull/251#issuecomment-916406936).
The old cherrypick is failed because of we don't have `auth-apiserver` deployments in 4.6
=> Add dedicated master support for ROKS 4[release-4.6]

assets/oauth-openshift/oauth-browser-client.yaml, assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
As per [convo](https://github.com/openshift/ibm-roks-toolkit/issues/151 ) change the  user-manifest-openshift-browser-client cm to secret.
I need to validated this on any one of the test cluster before merge into Master.
=> change the user-manifest-openshift-browser-client cm to secret

.secrets.baseline, assets/cluster-version-operator/cluster-version-operator-deployment.yaml, pkg/assets/bindata.go
Setting up an init container to remove the manifests for the 3CMO from
the cluster-version-operator. This will stop the 3CMO from being deployed
to the cluster, as it is not needed.
=> Omit 3CMO manifests from CVO

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, pkg/assets/bindata.go
Fix to match syntax used in [hypershift](https://github.com/openshift/hypershift/pull/265/files#diff-db006d6909a497e5d7bd7fb7371731bf2442a1ba9533d30f84842f71089e168eR28)
=> Fix syntax of CVO init container

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, pkg/assets/bindata.go
While the syntax used in the container works when editing a deployment,
ansible doesn't like parsing it. Fixing up the syntax to make ansible happy.
Verified that this actually works with a test cluster
```
test2          c660q0a003njarnqhfp0   normal   21 minutes ago   3         test       4.9.5_1241_openshift   Default               classic   
```
=> CVO initContainer syntax to work with ansible

assets/cluster-version-operator/cluster-version-operator-deployment.yaml, assets/control-plane-operator/cp-operator-deployment.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-apiserver/oauth-apiserver-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
Updated to support master pods to dedicated nodes for ROKS 4.9 on following components
Need to cherry pick to 4.9 Once code is merged.
=> Add nodeAffinity for Master Components

assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
In 4.6.48 a kube apiserver backport requires that the kube apiserver
config be initialized concurrently with the kube apiserver. This change
(which was made for 4.7) needs to be backported to 4.6 to allow the API
server to not crash.
Tested with 4.6.48 and 4.6.51
This change requires a change on the ansible side to add a `localhost-admin-kubeconfig` secret with a kubeconfig that talks to localhost in the same way that 4.7+ requires (https://github.com/openshift/ibm-roks-toolkit/pull/144)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2026146
=> Fixes for 4.6.48+

.secrets.baseline, assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Related to this issue to disable the kube-apiserver-profiling for ROKS 4.9: https://github.ibm.com/alchemy-containers/armada-update/issues/2771
=> ROKS v4.9: Disable Kubernetes API server profiling

.pre-commit-config.yaml, .secrets.baseline
Doing this to respin images for CVE remediation. Newly spun images will be
built on the 4.11 base due to https://github.com/openshift/release/pull/26103
=> Bump detect-secrets version

Dockerfile.cpoperator, Dockerfile.metrics
In order to switch to using a ubi base image, we need to avoid calling yum in Dockerfiles because it's not present.
=> Remove yum invocation from Dockerfiles

Dockerfile, Dockerfile.cpoperator, Dockerfile.metrics
The linked imagestream contains the base image for the toolkit.
=> Add reference to tookit base image in Dockerfiles

assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, pkg/assets/bindata.go
The cluster policy controller has a habit of crashing during rollouts
which can confuse the Kubernetes controller manager when minReadySeconds
is set. While we believe the root cause of the problem is a Kubernetes
controller manager bug (likely fixed in the latest releases), we are
going to remove minReadySeconds until we can confirm that the problem
is fully resolved.
=> Remove minReadySeconds from cluster policy controller

assets/kube-scheduler/config.yaml, pkg/assets/bindata.go
Kubernetes scheduler configuration must now use the v1beta2 API
for OpenShift version 4.10.
=> Use kubescheduler.config.k8s.io/v1beta2 API

.secrets.baseline, assets/cluster-version-operator/cluster-version-operator-deployment.yaml, pkg/assets/bindata.go
Removing the init container and payload logic added in https://github.com/openshift/ibm-roks-toolkit/pull/284.
The PRs referenced in the init container's comment have been merged.
=> Remove CVO init container

pkg/controllers/openshiftapiserver/controller.go, pkg/controllers/openshiftcontrollermanager/operator_client.go
Fixes a bug in the merge functions for both openshift apiserver and
openshift controller manager configuration. The merge was not doing a
delete of existing keys if the key was not present in the update,
causing continuous updates.
Backport of #406 minus unit tests
=> [release-4.9] Fix config observer updates

assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-apiserver/oauth-apiserver-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, pkg/assets/bindata.go
Remove minReadySeconds from deployments until [1] is fixed.
[1] https://github.com/kubernetes/kubernetes/issues/108266
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/420.
=> [release-4.7] Remove minReadySeconds from deployments

assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, pkg/assets/bindata.go
Remove minReadySeconds from deployments until [1] is fixed.
[1] https://github.com/kubernetes/kubernetes/issues/108266
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/420.
=> [release-4.6] Remove minReadySeconds from deployments

assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-apiserver/oauth-apiserver-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, pkg/assets/bindata.go
Remove minReadySeconds from deployments until [1] is fixed.
[1] https://github.com/kubernetes/kubernetes/issues/108266
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/420.
=> [release-4.8] Remove minReadySeconds from deployments

assets/kube-apiserver/kube-apiserver-deployment.yaml, pkg/assets/bindata.go
Related to this issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2902 to fix the ROKS 4.8 to 4.9 
upgrade instruction errors
**DNM until test results have been shared below**
=> DNM: Add Host_IP to kube-apiserver deployment to fix apirequestcount errors in ROKS 4.8

hack/create-release.sh, hack/wait-for-images.sh
Adds a script that waits for an imagestream tag built from the current git commit. If after ~ 45 min an image is not found, the job will fail. To retry it, another commit (with an arbitrary change) will need to be merged.
=> Wait for image stream tag to reflect current commit before creating a release

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Disable the PodSecury admission plugin for 4.10 to match OCP.
Partially implements https://github.ibm.com/alchemy-containers/armada-update/issues/3032
=> Disable PodSecurity in v4.10

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
PodSecurity is currently enabled in OCP 4.11. This updates our
kube-apiserver configuration with the same pluginConfig and
enabled-admission-plugin list.
Partially implements https://github.ibm.com/alchemy-containers/armada-update/issues/3032
=> Enable PodSecurity in 4.11

assets/kube-apiserver/kube-apiserver-deployment.yaml, assets/kube-controller-manager/kube-controller-manager-deployment.yaml, assets/kube-scheduler/kube-scheduler-deployment.yaml, assets/oauth-apiserver/oauth-apiserver-deployment.yaml, assets/oauth-openshift/oauth-server-deployment.yaml, assets/openshift-apiserver/openshift-apiserver-deployment.yaml, assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml, assets/roks-metrics/roks-metrics-deployment.yaml, assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml, pkg/assets/bindata.go
When the kube-apiserver deployment's priority class was increased all
the kube-server pods were deleted at the same time leading to a 2 - 3
minute kube-apiserver outage. It was determined this was due to
maxSurge: 3 giving us 3 new pods and the scheduler preempting (deleting)
the old pods becausae the new pods had a higher priority. Setting
maxSurge: 0 fixes (or at least works around) that problem. We also
found that maxSurge: 0 fixed the problem with minReadySeconds breaking
rollouts.
- Set maxSurge: 0 for deployments with multiple replicas
- Restore the minReadySeconds setting previously deleted
Fixes https://github.ibm.com/alchemy-containers/armada-update/issues/3237
Fixes https://github.ibm.com/alchemy-containers/armada-update/issues/3011
=> update maxSurge and minReadySeconds

assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml, pkg/assets/bindata.go
minReadySeconds was removed in https://github.com/openshift/ibm-roks-toolkit/pull/391
It is safe to restore that now that we are using maxSurge: 0
Partially implements https://github.ibm.com/alchemy-containers/armada-update/issues/3011
=> Restore minReadySeconds for cluster-policy-controller

Makefile, pkg/controllers/cmca/configmap_observer.go, pkg/controllers/openshiftapiserver/controller.go, pkg/controllers/openshiftcontrollermanager/operator_client.go, pkg/metrics/server.go, pkg/metricspusher/pusher.go
Bumping to gosec v2.12.0, and removing most of the check exclusions
that we had in place before.
Also verifying that the verify-gosec check behaves properly in the CI.
=> Enable most gosec checks

assets/cluster-bootstrap/00000_namespaces-needed-for-monitoring.yaml, pkg/assets/bindata.go
When user workload monitoring is enabled, we get alerts related to
ServiceMonitors using bearer tokens. Adding the
openshift.io/user-monitoring="false" label tells user workload
monitoring to skip this namespace. Since they aren't labeled as
cluster-monitoring, we've effectively told both cluster and user
workload monitoring to ignore the ServiceMonitors.
=> Add openshift.io/user-monitoring label to ns

assets/cluster-bootstrap/api-usage.yaml, assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml, assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml, pkg/assets/bindata.go
Update PrometheusRules for removed API alerts.
See https://github.ibm.com/alchemy-containers/armada-update/issues/3603
Add RBAC for podsecurity-admission-label-syncer.
See https://github.ibm.com/alchemy-containers/armada-update/issues/3522#issuecomment-47389184
=> Misc. 4.11 PrometheusRule and RBAC updates

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/3600
Change is to match OpenShift's cluster-kube-apiserver-operator changes https://github.com/openshift/cluster-kube-apiserver-operator/commit/8350321eb6d61629e1fb5bdf019200d6cda4c0be.
=> enforce privileged by default instead of restricted

Dockerfile, Dockerfile.cpoperator, Dockerfile.metrics, Makefile, go.mod, hack/releaser/Dockerfile, pkg/assets/bindata.go, pkg/controllers/testconfigobserver/configobserver.go
Updateing the Dockerfiles to use a 1.19 golang image when building the toolkit code. Also bumped the gosec version to v2.14.0
=> Update go version to 1.19

assets/kube-apiserver/kube-apiserver-deployment.yaml, pkg/assets/bindata.go
- Extending existing grace period from 90 to 120 seconds
- Adding env var for shutdown delay ( default to 90 seconds )
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>
=>  Adding graceful shutdown delay interval

.secrets.baseline, assets/route-controller-manager/config.yaml, assets/route-controller-manager/route-controller-manager-config-configmap.yaml, assets/route-controller-manager/route-controller-manager-deployment.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go, pkg/render/manifests.go
Partially based on: https://github.com/openshift/hypershift/pull/1756 and https://github.com/openshift/hypershift/pull/1790
=> Added route controller manager

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Details on new OpenShift admission plugin:
https://github.com/openshift/cluster-kube-apiserver-operator/blob/3e62b53e39db960ccc16d717d1a25d751d4e9c49/bindata/assets/config/defaultconfig.yaml#L100
```
storage.openshift.io/CSIInlineVolumeSecurity
```
- RH Jira: https://issues.redhat.com/browse/STOR-829
- PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1385
- Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-inline-vol-security.md
The admission plugin has been added and enabled by default in OCP 4.13.
Background:
The admission plugin adds extra checks for CSI drivers that enabled this `Ephemeral` volume lifecycle mode (like this: https://github.com/openshift/csi-driver-shared-resource-operator/blob/7f4d3da21d129153bad447562d81a92 …
=> Add new OCP 4.13 storage admission plugin

assets/cluster-bootstrap/deployer-clusterrole.yaml, assets/cluster-bootstrap/deployer-clusterrolebinding.yaml, pkg/assets/bindata.go
ROKS `v4.13` OCP conformance testing uncovered missing system:deployer cluster role/clusterrolebinding. Adding to cluster bootstrapping.
=> Add missing system:deployer ClusterRoleBinding

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Adds strict-transport-security-directives to the KubeApiServerConfig.
=> Enable strict-transport-security for kube-apiserver

assets/kube-apiserver/cluster-featuregate.yaml, assets/kube-apiserver/featuregate.yaml, assets/kube-apiserver/kube-apiserver-deployment.yaml, pkg/assets/bindata.go
During ROKS 4.14 bringup, it was was discovered that `featuregate` information is now required.
```
$ kubectl logs -n master-cin9ks420488vf8s9beg kube-apiserver-54757949cd-jz4gd -c config-bootstrap
F0712 17:27:36.225575       8 render.go:53] problem with featuregate manifests: cannot return FeatureGate without rendered manifests
cp: cannot stat '/tmp/output/manifests/*': No such file or directory
```
=> Featuregate information now required

pkg/render/manifests.go
Follow up PR (fix) for https://github.com/openshift/ibm-roks-toolkit/pull/776 to render the cluster featuregate configmap.
=> Render cluster featuregate configmap

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Enforce `restricted` pod security (now the default in OCP `v4.14`).
=> Enforce restricted pod security

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Reconcile enabled admission plugins in `ibm-roks-toolkit`  `kube-apiserver` config with `openshift` `cluster-kube-apiserver-operator` config.
Note: At the moment, `hypershift control plane operator` `kas` config does NOT match and is missing admission plugin added to `ibm-roks-toolkit` `kube-apiserver` config.
Additional information on the admission plugin being added: https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#before-you-begin
=> Reconcile admission plugins

assets/kube-apiserver/featuregate.yaml, cluster.yaml.example, pkg/api/types.go, pkg/assets/bindata.go
With addition of new featuregate vars, we are able to have a 'dynamic' featuregate config.
See test plan [comment](https://github.com/openshift/ibm-roks-toolkit/pull/806#issuecomment-1703081750) for testing performed.
For reference: this is the current working/tested config (which is 'statically' set and was only temporary while a 'dynamic' solution was worked out).
```
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
name: cluster
spec:
featureSet: CustomNoUpgrade
customNoUpgrade:
enabled:
- RotateKubeletServerCertificate
disabled:
- RetroactiveDefaultStorageClass
```
=> Update to dynamic featuregate config

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Change due to recent update in OCP 4.14 (https://github.com/openshift/api/pull/1575)
=> Set default pod security enforcement to privileged

assets/kube-apiserver/config.yaml, pkg/assets/bindata.go
Help to mitigate HTTP/2 attacks on the Kubernetes API Server
=> Set goaway-chance on kube-apiserver to 0.001

assets/openshift-apiserver/config.yaml, pkg/assets/bindata.go
This is meant to mirror changes made to core OpenShift via https://github.com/openshift/cluster-openshift-apiserver-operator/commit/cad9746b62abf3b3230592d45f7f60bcecc96dac
=> Add shutdown-duration-delay to openshift-apiserver

assets/kube-apiserver/featuregate.yaml, cluster.yaml.example, pkg/assets/bindata.go
Problem:
Featuregate rendering fails when there is more than one enabled or disabled featuregate. 
```
(initialize-manifests container log)
Warning: resource featuregates/cluster is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
The FeatureGate "cluster" is invalid: spec.customNoUpgrade.enabled[0]: Invalid value: "RotateKubeletServerCertificate    - cloudDualStackNodeIPs": spec.customNoUpgrade.enabled[0] in body should match '^([A-Za-z0-9-]+\.)*[A-Za-z0-9-]+\.?$'
```
(roks toolkit - demonstrating error with more than one enabled featuregate)
```
kind: ConfigMap …
```
=> Featuregate config rendering fix

assets/konnectivity/konnectivity-agent-control-plane-deployment.yaml, assets/konnectivity/konnectivity-agent-data-plane-daemonset.yaml, assets/kube-apiserver/kube-apiserver-egress-config-configmap.yaml, pkg/assets/bindata.go
- to avoid APIService flapping
- use more aggressive timers for connection management - agents will connect earlier if the server connection breaks
`sync-interval` - The initial interval by which the agent periodically checks if it has connections to all instances of the proxy server.
`probe-interval` - The interval by which the agent periodically checks if its connections to the proxy server are ready.
`sync-interval-cap` - The maximum interval for the SyncInterval to back off to when unable to connect to the proxy server.
Defaults are sync-interval:1s, probe-interval:1s and sync-interval-cap:10s.
=> Konnectivity update: use clusterIP service instead of localhost in kube-api egress config

.secrets.baseline, assets/kube-apiserver/kube-apiserver-deployment.yaml, pkg/assets/bindata.go
Don't reload on config changes to prevent issues with upgrade scenarios in the future (removing kms v1 provider). That is, for the rolling upgrade, we don't want the original containers to crash if the kms-config changes are incompatible.
=> Disable KMS automatic config reload

assets/konnectivity/konnectivity-agent-data-plane-daemonset.yaml, pkg/assets/bindata.go
- Fix coreDNS interworking
- With the change, konnectivity-agent in data plane will use the name resolution configuration from the node
- This makes sure that the konnectivity-agent's `proxy-server-url` can be resolved even if coreDNS is down or mis-configured (e.g. VPE gateway can be resolved by VPC pDNS) 
- konnectivity-agent control plane shall not change as it still needs to use coreDNS as in that case a ClusterIP Service is configured as `proxy-server-url`
=> use dnsPolicy: Default for konnectivity-agent in data plane

assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
We need to readjust the regex to reflect changes in how the machine config operator CRDs are named.
=> Remove '-operator' from machine config crd copy command

assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml, pkg/assets/bindata.go
We need to include only GA CRDs in 4.16.
=> Exclude NoUpgrade CRDs

assets/kube-apiserver/config.yaml, assets/openshift-controller-manager/config.yaml, pkg/assets/bindata.go
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/1034 to release-4.16.
=> ROKS v4.16: Set default pod security enforcement to restricted to align with openshift defaults.

assets/kube-apiserver/config.yaml, assets/openshift-controller-manager/config.yaml, pkg/assets/bindata.go
Reverts https://github.com/openshift/ibm-roks-toolkit/pull/1034 now that OpenShift has changed their mind regarding pod security admission enforcement in OpenShift 4.16 (moving back to privileged by default https://github.com/openshift/api/pull/1912/).  Requires cherry-pick back to `release-4.16`.
=> revert PR #1034, set default pod security enforcement back to privileged

hack/wait-for-images.sh
There is a slowdown in the CI, we need to wait longer for jobs to finish
=> Bump timeout in wait-for-images
