openshift/ibm-roks-toolkit

- pkg/controllers/clusteroperator/reconcile.go
Bring in latest updates from hypershift-toolkit
> Update to commit 50eb616

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- cluster.yaml.example
- pkg/api/types.go
- pkg/assets/bindata.go
Adding a kms container to the kube-apiserver pod if the kms info is provided
> Add support for kms secret encryption

- cmd/control-plane-operator/main.go
- go.mod
- pkg/cmd/cpoperator/operator-config.go
- pkg/controllers/openshift_apiserver_monitor/controller.go
- pkg/controllers/openshift_apiserver_monitor/setup.go
Fixes https://github.com/openshift/ibm-roks-toolkit/issues/22
> Add controller to monitor openshift apiserver

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- pkg/assets/bindata.go
Enable KMS to utilize a wrapped DEK stored in a secret.
> byok mount wdek secret

- assets/kube-scheduler/config.yaml
- pkg/api/defaults.go
- pkg/assets/bindata.go
Updates assets for 4.6 support
> Asset modifications needed for OCP 4.6

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- pkg/assets/bindata.go
Identifies the file path containing the current state of the Key Protect key state.
> Add Key Protect key state path

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- pkg/assets/bindata.go
> [release-4.4] Add Key Protect key state path

- assets/roks-metrics/roks-metrics-deployment.yaml
- pkg/assets/bindata.go
- pkg/render/manifests.go
Render metrics only when specified in the config
> Make metrics component rendering optional and fix metrics deployment

- pkg/controllers/clusteroperator/reconcile_test.go
This attempts to fix a race in the tests when using the fake client and lister
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/12758/rehearse-12758-pull-ci-openshift-ibm-roks-toolkit-master-unit/1316035749979623424
> Add wait.Poll to race fake client test

- Dockerfile.metrics
- Makefile
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/roks-metrics/roks-metrics-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-service.yaml
- assets/roks-metrics/roks-metrics-push-gateway-servicemonitor.yaml
- cmd/metrics-pusher/main.go
- pkg/assets/bindata.go
- pkg/metrics_pusher/pusher.go
- pkg/render/manifests.go
> [release-4.5] Use Prometheus PushGateway to push CVO metrics to user cluster

- pkg/api/defaults.go
Reverts openshift/ibm-roks-toolkit#88
> Revert "Update feature flags to mirror OCP"

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- pkg/assets/bindata.go
Running the container by itself I observed max 3m CPU and 36Mi memory usage.
> Add resource requests to metrics pusher sidecar

- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- assets/roks-metrics/roks-metrics-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
- cluster.yaml.example
- pkg/api/types.go
- pkg/assets/bindata.go
Add the ability to force master components to runAsUser
> Added securityContext runAsUser to master components

- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/roks-metrics/roks-metrics-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
- assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
- cluster.yaml.example
- pkg/assets/bindata.go
Fixed SecurityContext for roks metrics and manifest bootstrapper
> Updated more components to be compatible with running as non root

- pkg/api/defaults.go
These defaults will be tracked along with the other enabled/disabled
feature gates in the IBM code.
> Remove default feature gates

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- cluster.yaml.example
- pkg/api/types.go
- pkg/assets/bindata.go
Backport Portieris commits from master into `release-4.5`.
> Portieris 4.5 backport

- .secrets.baseline
- DockerCITest
- cluster.yaml.example
Changes any references of registry.svc.ci.openshift.org to registry.ci.openshift.org
> Update registry references

- .secrets.baseline
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/control-plane-operator/cp-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-apiserver/oauth-apiserver-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2037
> Update defaultMode 0640 for all secret volume definitions

- .secrets.baseline
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/control-plane-operator/cp-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2037
> Update defaultMode 0640 for all secret volume definitions: release-4.6

- .secrets.baseline
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2035
> Add --profiling=false to kube-controller-manager - release-4.6

- .secrets.baseline
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/control-plane-operator/cp-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2037
> Update defaultMode 0640 for all secret volume definitions: release-4.5

- .secrets.baseline
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2035
> Add --profiling=false to kube-controller-manager - release-4.5

- assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
- pkg/assets/bindata.go
fix an insecure volume mount for the manifests-bootstrapper pod.
> fix an insecure volume mount for the manifests-bootstrapper pod

- README.md
Current images are impacted by CVEs. Need to rebuild to remediate.
> Empty change to force new image builds

- assets/cluster-version-operator/cluster-version-operator-configmap.yaml
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/cluster-version-operator/cluster-version-operator-secret.yaml
- cmd/metrics-pusher/main.go
- pkg/assets/bindata.go
- pkg/metrics_pusher/pusher.go
Add certs for CVO & Metrics pusher container to serve cvo metrics over https
> Add certs to CVO to serve metrics over https

- README.md
Small change to the README to proc new releases and new images
> Respin images for CVE remediation

- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/control-plane-operator/cp-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-apiserver/oauth-apiserver-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
- pkg/assets/bindata.go
Verified changes locally, seems like the merge request created by [robot](https://github.com/openshift/ibm-roks-toolkit/pull/253) has some issues, because of which verification check is failing.
Perhaps, we can close the PR#253 and review this PR to cherry pick PR#251 into release 4.7
> Add dedicated master support for ROKS [release-47]

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
Refrences updated to point to latest release.
> Update comments in Dockerfiles

- cluster.yaml.example
> [release-4.7] Update cluster yaml example

- .secrets.baseline
- cluster.yaml.example
> [release-4.6] Update cluster yaml example

- .secrets.baseline
- assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2569
> Update removed kubectl --dry-run option without value

- assets/cluster-bootstrap/cluster-ingresscontrollers-02-config.yaml
- pkg/assets/bindata.go
The IngressController template has a bug in it. This change is to fix that.
> Fix the template of the default IngressController

- .secrets.baseline
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-apiserver/oauth-apiserver-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2751
>  Update minReadySeconds and terminationGracePeriod for ROKS 4.8

- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-apiserver/oauth-apiserver-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2751
> Update minReadySeconds and terminationGracePeriod for ROKS 4.7

- .secrets.baseline
- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2751
> Update minReadySeconds and terminationGracePeriod for ROKS 4.6

- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2751
> Add liveness/readiness probes to components

- .pre-commit-config.yaml
- .secrets.baseline
Manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/356
> [release-4.8] Bump detect-secrets version

- .pre-commit-config.yaml
- .secrets.baseline
Manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/356
> [release-4.7] Bump detect-secrets version

- .pre-commit-config.yaml
- .secrets.baseline
Manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/356
> [release-4.6] Bump detect-secrets version

- .secrets.baseline
- assets/kube-apiserver/config.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2916
> Remove deprecated ports for 4.10

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/383
> [release-4.9] Add reference to toolkit base image in Dockerfiles

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/383
> [release-4.7] Add reference to toolkit base image in Dockerfiles

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
This is a manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/383
> [release-4.6] Add reference to toolkit base image in Dockerfiles

- hack/create-git-release.sh
Adds an origin remote if not set
> Add remote on release

- hack/create-git-release.sh
Filename doesn't include a `v`
> release debug: fix filename to upload for release

- hack/create-git-release.sh
- hack/tag-release-images.sh
- hack/untag-release-images.sh
Makes the release tag the same as previous releases
> Add '.0' to release version in tag

- hack/create-git-release.sh
- hack/tag-release-images.sh
- hack/untag-release-images.sh
Fixes release tag name and upload file name in scripts.
> Release script fixes

- .secrets.baseline
- assets/kube-apiserver/config.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/2752
> Add shutdown-send-retry-after=true to kube-apiserver

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-apiserver/oauth-apiserver-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- assets/roks-metrics/roks-metrics-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
- pkg/assets/bindata.go
Manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/491
> [release-4.7] update maxSurge and minReadySeconds

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-apiserver/openshift-apiserver-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- assets/roks-metrics/roks-metrics-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
- pkg/assets/bindata.go
Manual cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/491
> [release-4.6] update maxSurge and minReadySeconds

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
- go.mod
- go.sum
- hack/releaser/Dockerfile
This will be used by releases 4.11+
> Move to golang 1.18

- assets/cluster-bootstrap/api-usage.yaml
- assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- assets/cluster-bootstrap/csr_approver_clusterrole.yaml
- assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/trust_distribution_role.yaml
- assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
- pkg/assets/bindata.go
> Update OpenShift assets for 4.11

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
> Update Dockerfile to point to correct 1.18 image

- Dockerfile.metrics
- assets/cluster-bootstrap/api-usage.yaml
- assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- assets/cluster-bootstrap/csr_approver_clusterrole.yaml
- assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/trust_distribution_role.yaml
- assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
- pkg/assets/bindata.go
Syncing with 4.10 versions of assets
> [release-4.10] Update OpenShift assets

- assets/cluster-version-operator/cluster-version-operator-deployment.yaml
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- assets/roks-metrics/roks-metrics-deployment.yaml
- assets/roks-metrics/roks-metrics-push-gateway-deployment.yaml
- pkg/assets/bindata.go
Related to this issue: https://github.ibm.com/alchemy-containers/armada-update/issues/3299
> ROKS 4.11: Update roks toolkit image policies

- assets/cluster-bootstrap/api-usage.yaml
- assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- assets/cluster-bootstrap/csr_approver_clusterrole.yaml
- assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-alert.yaml
- assets/cluster-bootstrap/trust_distribution_role.yaml
- assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
- pkg/assets/bindata.go
> Update OpenShift assets for 4.12

- assets/kube-scheduler/config.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/3605
> use kubescheduler.config.k8s.io/v1 API

- assets/kube-apiserver/config.yaml
- pkg/assets/bindata.go
Related: https://ibm-argonauts.slack.com/archives/C6WTRUSCB/p1667214596017549?thread_ts=1667214417.519039&cid=C6WTRUSCB
> enforce restricted PodSecurityConfiguration by default

- hack/releaser/Dockerfile
The yum installation is messed up by rhel 8
> Install hub binary from source

- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml
- pkg/assets/bindata.go
Targeted cherry-pick of https://github.com/openshift/ibm-roks-toolkit/pull/749
> Fix typo in PSA clusterrole

- assets/kube-apiserver/featuregate.yaml
- pkg/assets/bindata.go
Wrong apiversion specified in featuregate config.
> Update apiversion for featuregate config

- assets/kube-apiserver/kube-apiserver-deployment.yaml
- pkg/assets/bindata.go
Need to render and apply featuregate status.
> Render featuregate status

- assets/route-controller-manager/route-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/4900
> reconfigure route-controller-manager deployment

- Dockerfile
- Dockerfile.cpoperator
- Dockerfile.metrics
Non-root user should be added when building the images.
> Add non root user to Dockerfiles

- assets/cluster-bootstrap/api-usage.yaml
- assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- assets/cluster-bootstrap/csr_approver_clusterrole.yaml
- assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
- assets/cluster-bootstrap/deployer-clusterrole.yaml
- assets/cluster-bootstrap/deployer-clusterrolebinding.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-alert.yaml
- assets/cluster-bootstrap/trust_distribution_role.yaml
- assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
- cmd/control-plane-operator/main.go
- pkg/assets/bindata.go
- pkg/config/file.go
- pkg/metricspusher/pusher.go
- pkg/render/rendercontext.go
Synchronized assets with upstream
> Currency updates for 4.14

- assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml
- assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/leader-ingress-to-route-controller-role.yaml
- assets/cluster-bootstrap/leader-ingress-to-route-controller-rolebinding.yaml
- pkg/assets/bindata.go
Syncing more assets and pointing to source locations
> Additional currency updates for 4.14

- .secrets.baseline
- assets/oauth-openshift/oauth-cli-client.yaml
- pkg/assets/bindata.go
- pkg/render/manifests.go
Related: https://github.ibm.com/alchemy-containers/armada-update/issues/5227
> Add oauth CLI client for web based login

- assets/konnectivity/konnectivity-agent-control-plane-deployment.yaml
- pkg/assets/bindata.go
Related: https://github.ibm.com/alchemy-containers/armada-update/issues/5243
> Update Konnectivity to honor config replicas

- assets/openshift-controller-manager/config.yaml
- pkg/assets/bindata.go
Related: https://github.ibm.com/alchemy-containers/armada-update/issues/5349
> Disable OpenShift PSA feature flag on cluster policy controller

- assets/cluster-bootstrap/api-usage.yaml
- assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- assets/cluster-bootstrap/csr_approver_clusterrole.yaml
- assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
- assets/cluster-bootstrap/deployer-clusterrole.yaml
- assets/cluster-bootstrap/deployer-clusterrolebinding.yaml
- assets/cluster-bootstrap/etcd-operator-config.yaml
- assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml
- assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/leader-ingress-to-route-controller-role.yaml
- assets/cluster-bootstrap/leader-ingress-to-route-controller-rolebinding.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrole.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-alert.yaml
- assets/cluster-bootstrap/trust_distribution_role.yaml
- assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
- pkg/assets/bindata.go
> Asset sync 4.15

- .secrets.baseline
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- pkg/assets/bindata.go
Related: https://github.ibm.com/alchemy-containers/armada-update/issues/5330
> Asset sync for OpenShift version 4.15 GA

- cluster.yaml.example
Minor update (spelling error) to cluster yaml example. Not urgent. Merge, but no need to cut a new release just for it.
Just pull in the next time we need to publish a new release.
> Minor update cluster yaml example

- .secrets.baseline
- assets/kube-apiserver/config.yaml
- pkg/assets/bindata.go
Related: https://github.com/kubernetes/kubernetes/issues/118777
> Do not have Kubernetes API server reconcile its endpoint

- hack/tag-release-images.sh
- hack/wait-for-images.sh
To help debug any issues with the kubeconfig
> Add oc whoami to release scripts

- .secrets.baseline
- assets/kube-apiserver/kube-apiserver-deployment.yaml
- pkg/assets/bindata.go
Related: https://github.com/openshift/hypershift/pull/3443
> Render IBM Cloud managed cluster profile for KAS bootstrap

- assets/kube-apiserver/config.yaml
- pkg/assets/bindata.go
Issue: https://github.ibm.com/alchemy-containers/armada-update/issues/5679
> Disable PersistentVolumeLabel admission plugin

- go.mod
- go.sum
- vendor/github.com/emicklei/go-restful/v3/CHANGES.md
- vendor/github.com/emicklei/go-restful/v3/constants.go
- vendor/github.com/emicklei/go-restful/v3/request.go
- vendor/github.com/emicklei/go-restful/v3/response.go
- vendor/github.com/emicklei/go-restful/v3/route.go
- vendor/modules.txt
Resolving issues identified by prisma twistlock
> [release-4.13] Prisma go dep updates

- Dockerfile.metrics
Addresses prisma twistlock findings
> Bump pushgateway to version 1.9.0

- assets/cluster-bootstrap/api-usage.yaml
- assets/cluster-bootstrap/apiserver-apirequestcounts-crd.yaml
- assets/cluster-bootstrap/cluster-network-01-crd.yaml
- assets/cluster-bootstrap/csr_approver_clusterrole.yaml
- assets/cluster-bootstrap/csr_approver_clusterrolebinding.yaml
- assets/cluster-bootstrap/deployer-clusterrole.yaml
- assets/cluster-bootstrap/deployer-clusterrolebinding.yaml
- assets/cluster-bootstrap/etcd-operator-config.yaml
- assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml
- assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/leader-ingress-to-route-controller-role.yaml
- assets/cluster-bootstrap/leader-ingress-to-route-controller-rolebinding.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrole.yaml
- assets/cluster-bootstrap/namespace-security-allocation-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrole.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-privileged-namespaces-syncer-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrole.yaml
- assets/cluster-bootstrap/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
- assets/cluster-bootstrap/podsecurity-alert.yaml
- assets/cluster-bootstrap/trust_distribution_role.yaml
- assets/cluster-bootstrap/trust_distribution_rolebinding.yaml
- pkg/assets/bindata.go
> Asset sync 4.17

- assets/kube-controller-manager/kube-controller-manager-deployment.yaml
- assets/kube-scheduler/kube-scheduler-deployment.yaml
- assets/oauth-openshift/oauth-server-deployment.yaml
- assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
- assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
- assets/route-controller-manager/route-controller-manager-deployment.yaml
- pkg/assets/bindata.go
Matching the changes being made in HyperShift via
https://github.com/openshift/hypershift/pull/4738
> Run 2 replicas of active/passive HA deployments

- assets/konnectivity/konnectivity-agent-control-plane-deployment.yaml
- assets/konnectivity/konnectivity-agent-data-plane-daemonset.yaml
- pkg/assets/bindata.go
This PR adds readiness probe to Konnectivity userplane agents.
> add Konnectivity agent readiness

- OWNERS
/cherry-pick release-4.17 release-4.16 release-4.15 release-4.14
> Add Joseph-Goergen to OWNERS file
